import '../styles/globals.css'
import type { AppProps } from 'next/app'
import styles from '../styles/Home.module.scss'
import Head from 'next/head'
import { blue } from '@mui/material/colors';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { Fragment, useState } from 'react'
import { BottomNavigation, BottomNavigationAction } from '@mui/material'
import AccessTimeIcon from '@mui/icons-material/AccessTime';
import TimelineIcon from '@mui/icons-material/Timeline';
import MapIcon from '@mui/icons-material/Map';

import Link from 'next/link'

function MyApp({ Component, pageProps }: AppProps) {
  const [value, setValue] = useState(0);

  const theme = createTheme({
    palette: {
      mode: 'dark',
    },
  });

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Clock Pi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik+Dirt&display=swap" rel="stylesheet" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <main className={styles.container}>
        <div className={styles.main}>
          <Component {...pageProps} />
        </div>
        <BottomNavigation
          showLabels
        >
          <Link href="/"><BottomNavigationAction label="Time" icon={<AccessTimeIcon />} /></Link>
          <Link href="/money"><BottomNavigationAction label="Money" icon={<TimelineIcon />} /></Link>
          <Link href="/map"><BottomNavigationAction label="Map" icon={<MapIcon />} /></Link>
        </BottomNavigation>
      </main>
    </ThemeProvider>
  )
}

export default MyApp
