import '../styles/globals.css'
import type { AppProps } from 'next/app'
import styles from '../styles/Home.module.scss'
import Head from 'next/head'
import { Fragment } from 'react'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>Clock Pi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <main className={styles.container}>
        <div className={styles.main}>
          <Component {...pageProps} />
        </div>
      </main>
    </Fragment>
  )
}

export default MyApp
